Basic block breaking and placing
PrismarineJS/prismarine-viewer pull request #134
Opened 2021-02-06 20:51 UTC by ShrimpyStuff

2021-02-08 01:13 UTC, extremeheat requested changes
You should lint the file, there's formatting errors

2021-02-08 01:13 UTC, extremeheat commented on examples/web_client/index.js
> +        const Vec3 = require('vec3').Vec3;
require this at the top of the file

2021-02-08 01:13 UTC, extremeheat commented on examples/web_client/index.js
> +
empty condition here

2021-02-08 19:20 UTC, ShrimpyStuff commented on examples/web_client/index.js
> +
Yeah I forgot about that

2021-02-08 19:21 UTC, ShrimpyStuff commented on examples/web_client/index.js
> +        const Vec3 = require('vec3').Vec3;
Yeah, I could do that

2021-02-12 19:05 UTC, closed without merging

2021-02-12 20:39 UTC, rom1504 commented
Any reason to close it ?

2021-02-12 20:40 UTC, u9g commented
> Any reason to close it ?

reopened here https://github.com/PrismarineJS/prismarine-viewer/pull/138

2021-02-17 00:12 UTC, ShrimpyStuff commented
I closed it because I deleted the repo before I could finish it