Move clickBlock event to core api
PrismarineJS/prismarine-viewer pull request #90
Opened 2020-12-21 17:21 UTC by Karang

2020-12-21 18:33 UTC, rom1504 requested changes
Doesn't that make the viewer only usable inside a browser ?
What's the dom for headless ?

2020-12-21 18:51 UTC, Karang commented
> Doesn't that make the viewer only usable inside a browser ?
> What's the dom for headless ?

The domElement is the canvas, headless is faking the canvas api, so it still work in headless mode, though I don't think it will actually generate events.

2020-12-21 19:41 UTC, rom1504 commented
Sounds good, can you just add that mouseClick event in the list of events I documented in the .md file (so it's possible for users to provide their own emitter) ?

2020-12-21 19:41 UTC, rom1504 approved these changes

2020-12-22 01:40 UTC, rom1504 approved these changes

2020-12-22 01:46 UTC, rom1504 approved these changes

2020-12-22 01:46 UTC, merged